### ISSUE TITLE
Survey in chat is still not working while it works for voice 

### ISSUE THREAD

**Issue by kannanrk85** [aws-samples/amazon-connect-contact-surveys#14]
Survey in chat is still not working while it works for voice

**Comment by aurelienaws** [comment]
Hi kannanrk85 - can you please describe the issue you are facing?

**Comment by aurelienaws** [comment]
kannanrk85 - correct, it seems an unwanted commit has made its way to the pipeline. Working on it now.

**Comment by aurelienaws** [comment]
This is now fixed. Please update your deployment with the latest Cloudformation template.

**Comment by kannanrk85** [comment]
@aurelienaws now it works  ,, but for chat it only gets response for first question. example if we have a 3 question chat it ends after we give first response.

**Comment by aurelienaws** [comment]
@kannanrk85, there seem to be rare occurrences where the Lex bot requires a manual shake up (likely due to the CFT deployment process). to overcome this, navigate to the Lex bot created by the solution in your AWS account and use Lex's test functionality to test the bot version 1 (labelled "Version 1"). In Lex's test widget, just type in a number (0 to 9), and you will receive a "Intent n fulfilled". Once completed, you should not see that issue anymore. I am investigating internally to understand how we can prevent this to happen for some deployments.

**Comment by emma77017** [comment]
I used the new yaml file in deployment and the chat survey result still doesn't show up. Even the first survey question

**Comment by emma77017** [comment]
@aurelienaws can you help to see why the result is still not showing for chat?

**Comment by aurelienaws** [comment]
Hi there - without a more complete description, it is not going to be easy to assist. I would suggest to review contact flow logs as a starter, to understand what is not working. The solution has been successfully tested in its latest version.

**Comment by emma77017** [comment]
so the call survey works well but the chat survey result won't show up in the result of the Published surveys in [Contact Surveys for Amazon Connect]. 

I did find an error in cloudwatch but it doesn't have much info:{
    "Results": "Error",
    "ContactId": "63df5504-62a1-44d6-bebd-bbefde6522b4",
    "ContactFlowId": "arn:aws:connect:us-west-2:702015403003:instance/62efe60e-146d-4fe9-9fe4-e487566e9a78/flow-module/a24cb356-daef-418d-9d07-1d9a11715a77",
    "ContactFlowName": "Contact Survey",
    "ContactFlowModuleType": "GetUserInput",
    "Identifier": "b80d83ff-6c6c-4917-a496-1acfb564c556",
    "Timestamp": "2024-04-18T22:55:46.941Z",
    "ModuleExecutionStack": [
        "arn:aws:connect:us-west-2:702015403003:instance/62efe60e-146d-4fe9-9fe4-e487566e9a78/flow-module/a24cb356-daef-418d-9d07-1d9a11715a77",
        "arn:aws:connect:us-west-2:702015403003:instance/62efe60e-146d-4fe9-9fe4-e487566e9a78/contact-flow/f0251ff6-1e12-4137-945a-faab3103c1a3"
    ]
}

**Comment by aurelienaws** [comment]
Correct, it's not going to provide enough for us to assist you. What can be said though is that your issue is specific to your environment. I'd recommend to:
- check that you are attaching a valid surveyId as a contact attribute before transferring to the Survey module (see the guide on how to use the solution)
- check the language used to handle these contacts. This solution deploys a Lex bot with a en_US locale. This means that Lex will expect the language set by Amazon Connect for these contact to match that locale.
